<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="IC2D">

    <!-- Definitons -->
    <xacro:property name="slider_upper" value="10.0" />
    <xacro:property name="slider_lower" value="-10.0" />
    <xacro:property name="slider_effort_lim" value="10000" />
    <xacro:property name="slider_damping" value="0.00" />

    <!-- Useful Macros -->

    <xacro:macro name="include_geometry_file" params="filename">
        <geometry>
            <mesh filename="file://$(find ic2d_urdf)/meshes/${filename}.STL"/>
        </geometry>
    </xacro:macro>

    <xacro:macro name="inertial_box" params="mass dx dy dz *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * mass * (dy*dy+dz*dz)}" ixy="0.0" ixz="0.0"
                     iyy="${(1/12) * mass * (dx*dx+dz*dz)}" iyz="0.0"
                     izz="${(1/12) * mass * (dx*dx+dy*dy)}" />
        </inertial>
    </xacro:macro>

    <!-- Specify some colours -->
    <!-- Rviz color -->
    <material name="nickel">
        <color rgba="${193/255} ${183/255} ${131/255} 1"/>
    </material>
    <!-- Gazebo color -->
    <gazebo reference="base_link">
        <material>
            Gazebo/Gold
        </material>
    </gazebo>

    <!-- This first link called "world" is empty -->

    <link name="world"></link>

    <joint name="slider_joint" type="prismatic">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="world"/>
        <child link="base_link"/>
        <axis xyz="1 0 0"/>
        <!-- calibration: the reference positions of the joint, 
        used to calibrate the absolute position of the joint. -->
        <!-- calibration rising="0.0" /--> 
        <!-- dynamics: an element specifying physical properties of the joint. 
        These values are used to specify modeling properties of the joint, 
        particularly useful for simulation.-->
        <dynamics damping="${slider_damping}" friction="0.0" />
        <limit lower="${slider_lower}" upper="${slider_upper}" velocity="340" effort="${slider_effort_lim}"/>
    </joint>

    <!-- Gazebo Joint Dynamics -->
    <gazebo reference="slider_joint">
        <implicitSpringDamper>true</implicitSpringDamper>
        <stopCfm>0.00010</stopCfm>
        <stopErp>0.1</stopErp> <!-- 0.2 is the default-->
        <springStiffness>0</springStiffness>
        <springReference>0</springReference>
        <!-- cfmDamping>1.00</cfmDamping -->
    </gazebo>

    <link name="base_link">
        <xacro:property name="base_global_mass" value="90.27" />
        <xacro:property name="base_global_length" value="1.305" />
        <xacro:property name="base_global_height" value="0.0254" />
        <xacro:property name="base_global_width" value="0.355" />
        <xacro:property name="base_ground_offset" value="0.00" />

        <xacro:property name="link_origin">
            <origin xyz="0 0 ${base_global_height/2 + base_ground_offset}" rpy="${pi/2} 0 0" />
        </xacro:property>

        <visual>
            <origin xyz="${-base_global_width/2} ${base_global_length/2} ${base_ground_offset}" rpy="${pi/2} 0 0" />
            <xacro:include_geometry_file filename="base_global"/>
            <material name="nickel" /> <!-- for Rviz   -->
        </visual>

        <collision>
            <xacro:insert_block name="link_origin" />
            <geometry>
                <box size="${base_global_width*0.90} ${base_global_height*0.90} ${base_global_length*0.90}" />
            </geometry>
        </collision>

        <xacro:inertial_box mass="${base_global_mass}" dx="${base_global_width}" 
                            dy="${base_global_height}" dz="${base_global_length}">
            <xacro:insert_block name="link_origin" />
        </xacro:inertial_box>

    </link>

    <!-- Necessary config/tags for ros2_control interface with Gazebo Classic -->
    <ros2_control name="GazeboSystem" type="system">
        <hardware>
            <plugin>gazebo_ros2_control/GazeboSystem</plugin>
        </hardware>

        <joint name="slider_joint">
            <command_interface name="position">
                <param name="min">{slider_lower}</param>
                <param name="max">{slider_upper}</param>
            </command_interface>

            <state_interface name="position">
                <param name="initial_value">0.0</param>
            </state_interface>

            <state_interface name="velocity">
                <param name="initial_value">0.0</param>
            </state_interface>

            <state_interface name="effort">
                <param name="initial_value">0.0</param>
            </state_interface>
        </joint>
    </ros2_control>

    <gazebo>
        <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
            <robot_param_node>robot_state_publisher</robot_param_node>
            <robot_param>robot_description</robot_param>
            <parameters>$(find ic2d_urdf)/config/ic2d_controllers.yaml</parameters>
        </plugin>
    </gazebo>

</robot>
