controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 2000

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    effort_controller:
      type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


joint_trajectory_controller:
  ros__parameters:
    joints:
      - slider_joint

    interface_name: position

    command_interfaces:
      - position

    state_interfaces:
      - position


effort_controller:
  ros__parameters:
    joints:
      - slider_joint